# Generated by Django 2.0 on 2021-08-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pic', models.ImageField(default='', upload_to='image/')),
                ('description', models.CharField(max_length=1000)),
                ('poston', models.FloatField(max_length=100)),
                ('postby', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.AlterField(
            model_name='schedule',
            name='pic',
            field=models.ImageField(default='', upload_to='image/'),
        ),
    ]
